Update tutorial screens
RenCarQuest/CarGuru pull request #2
Opened 2024-05-03 15:26 UTC by Giancarlo-Castaneda

Se refactorizan las pantallas del splash y el tutorial de uso para nuevos usuarios.
TODO
- [ ] agregar la información definida por producto, está en revisión

2024-05-05 00:46 UTC, ndmunoz10 requested changes

2024-05-05 00:46 UTC, ndmunoz10 commented on CarGurus App/lib/presentation/features/splash/splash_screen.dart
> +  getdarkmodepreviousstate() async {
Change method name to camelCase

2024-05-05 00:46 UTC, ndmunoz10 commented on CarGurus App/lib/presentation/features/splash/splash_screen.dart
> +    permission = await Geolocator.requestPermission();
Please re check this flow, we're checking if the permission is granted but still requesting it even if the permission is granted. Also, do we need to request for location permissions?

2024-05-06 23:38 UTC, Giancarlo-Castaneda commented on CarGurus App/lib/presentation/features/onboarding/onbording_screen.dart
> +                  index = value;
I implemented cubit but I still need to have an index in the screen file to be able to change the pagination indicator, do you know if there is a way to have this property within cubit? I can't find a way to modify a property of the cubit

2024-05-07 15:13 UTC, ndmunoz10 commented on CarGurus App/lib/presentation/features/onboarding/onbording_screen.dart
> +                  index = value;
Sure, you can add the index in the OnboardingState class and then create a method to set the new index to the current index, eg: `void setPageIndex(final int newIndex) { emit(state.copyWith(currentPage: newIndex)) }`. Then you can just listen for state changes on the Widget and update the UI that you need to update

2024-05-07 16:53 UTC, Giancarlo-Castaneda commented on CarGurus App/lib/presentation/features/onboarding/onbording_screen.dart
> +                  index = value;
done, thank you

2024-05-07 19:57 UTC, ndmunoz10 approved these changes

2024-05-07 19:57 UTC, merged